import { getProducts, getCategories, getKits, getSettings, getPublicContent } from "./data.js";

const I18N={
pt:{nav:{products:"Produtos",kits:"Rancho do mês",admin:"Administração"},hero:{badge:"Novo: Compras pelo WhatsApp",titleEnd:"sem sair de casa.",text:"Escolha os produtos, monte o carrinho e envie o pedido pelo WhatsApp. Simples, rápido e transparente.",cta:"Começar a comprar",how:"Ver como funciona",delivery:"Entrega Hoje",quality:"Qualidade"},categories:{subtitle:"Encontre tudo o que precisa para a sua despensa."},kits:{badge:"Destaques",text:"Kits pré-montados pensados para facilitar a sua rotina e garantir economia."},products:{title:"Produtos",text:"Escolha os produtos para o seu rancho."},how:{title:"Como funciona"},faq:{title:"Perguntas frequentes"},cart:{title:"Seu carrinho",total:"Total",checkout:"Finalizar pedido"},footer:{desc:"Qualidade do campo direto para a sua mesa, com a flexibilidade que o seu dia a dia pede.",links:"Links Úteis",contact:"Contacto",social:"Siga-nos",rights:"Todos os direitos reservados."}},
en:{nav:{products:"Products",kits:"Monthly bundle",admin:"Administration"},hero:{badge:"New: Order by WhatsApp",titleEnd:"without leaving home.",text:"Choose your products, build your cart and send the order by WhatsApp. Simple, fast and transparent.",cta:"Start shopping",how:"How it works",delivery:"Delivery Today",quality:"Quality"},categories:{subtitle:"Find everything you need for your pantry."},kits:{badge:"Highlights",text:"Pre-built bundles designed to simplify your routine and save money."},products:{title:"Products",text:"Choose products for your household."},how:{title:"How it works"},faq:{title:"Frequently asked questions"},cart:{title:"Your cart",total:"Total",checkout:"Checkout"},footer:{desc:"Quality from the field to your table, with flexibility for your everyday life.",links:"Useful links",contact:"Contact",social:"Follow us",rights:"All rights reserved."}},
zh:{nav:{products:"产品",kits:"本月套餐",admin:"管理",},hero:{badge:"新功能：WhatsApp 下单",titleEnd:"足不出户完成采购。",text:"选择商品、加入购物车并通过 WhatsApp 发送订单。简单、快捷、透明。",cta:"开始购物",how:"了解流程",delivery:"今日配送",quality:"品质保证"},categories:{subtitle:"找到您的家庭储藏所需的一切。"},kits:{badge:"精选",text:"预先搭配的套餐，帮助您轻松生活并节省开支。"},products:{title:"产品",text:"为您的家庭选择商品。"},how:{title:"购买流程"},faq:{title:"常见问题"},cart:{title:"购物车",total:"总计",checkout:"结算"},footer:{desc:"从农场到餐桌，为您的日常生活提供灵活选择。",links:"有用链接",contact:"联系方式",social:"关注我们",rights:"版权所有。"}},
fr:{nav:{products:"Produits",kits:"Panier du mois",admin:"Administration"},hero:{badge:"Nouveau : commande WhatsApp",titleEnd:"sans quitter la maison.",text:"Choisissez vos produits, composez votre panier et envoyez la commande par WhatsApp. Simple, rapide et transparent.",cta:"Commencer",how:"Comment ça marche",delivery:"Livraison aujourd'hui",quality:"Qualité"},categories:{subtitle:"Trouvez tout ce dont vous avez besoin pour votre garde-manger."},kits:{badge:"Sélection",text:"Des paniers prêts à l'emploi pour simplifier votre quotidien et économiser."},products:{title:"Produits",text:"Choisissez les produits pour votre foyer."},how:{title:"Comment ça marche"},faq:{title:"Questions fréquentes"},cart:{title:"Votre panier",total:"Total",checkout:"Passer la commande"},footer:{desc:"La qualité du champ directement à votre table, avec flexibilité.",links:"Liens utiles",contact:"Contact",social:"Suivez-nous",rights:"Tous droits réservés."}},
chg:{nav:{products:"Swilo",kits:"Rancho wa n'weti",admin:"Ulawuri"},hero:{badge:"Swa nyuwani: oda hi WhatsApp",titleEnd:"u nga humi kaya.",text:"Hlawula swilo, vekela eka cart kutani rhumela oda hi WhatsApp. Swa olova, swa hatlisa naswona swa vonaka.",cta:"Sungula ku xava",how:"Ndlela leyi swi tirhaka ha yona",delivery:"Ku yisa namuntlha",quality:"Nkoka"},categories:{subtitle:"Kuma swilo leswi u swi lavaka endlwini."},kits:{badge:"Swikombiso",text:"Tikhithi leti lunghisiweke ku olovisa siku ni siku."},products:{title:"Swilo",text:"Hlawula swilo swa ndyangu wa wena."},how:{title:"Ndlela leyi swi tirhaka ha yona"},faq:{title:"Swivutiso leswi talaka ku vutisiwa"},cart:{title:"Cart ya wena",total:"Ntsengo",checkout:"Hetisa oda"},footer:{desc:"Nkoka wa le masikwini wu fika etafuleni ra wena hi ku olova.",links:"Swihlanganisi",contact:"Ku tihlanganisa",social:"Hi landzele",rights:"Timfanelo hinkwato ti hlayisiwile."}}
};
const state={lang:localStorage.getItem("rf_lang")||"pt", products:[], categories:[], kits:[], settings:{}, cart:JSON.parse(localStorage.getItem("rf_cart")||"[]")};
const $=s=>document.querySelector(s);
const money=n=>`${Number(n||0).toLocaleString("pt-MZ",{minimumFractionDigits:2,maximumFractionDigits:2})} MZN`;
function tr(path){return path.split(".").reduce((o,k)=>o?.[k],I18N[state.lang])||path}
function applyI18n(){document.querySelectorAll("[data-i18n]").forEach(el=>el.textContent=tr(el.dataset.i18n));document.documentElement.lang=state.lang}
function current(v){return typeof v==="string"?v:(v?.[state.lang]||v?.pt||Object.values(v||{})[0]||"")}
function imgFor(p){return p.image_url||p.image||"https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=700&q=80"}
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.remove("hidden");setTimeout(()=>t.classList.add("hidden"),2500)}
async function load(){state.products=await getProducts();state.categories=await getCategories();state.kits=await getKits();state.settings=await getSettings();renderAll();applyI18n()}
function renderCategories(){const el=$("#categories");el.innerHTML=state.categories.map((c,i)=>`<button data-cat="${c.id}" class="group flex flex-col items-center justify-center p-4 rounded-[2rem] bg-white hover:bg-surface-container shadow-sm hover:shadow-md transition min-h-[140px] text-center"><div class="w-14 h-14 rounded-full bg-surface-container-low flex items-center justify-center text-primary group-hover:text-secondary"><span class="material-symbols-outlined">${c.icon||["rice_bowl","lunch_dining","bakery_dining","storefront","oil_barrel"][i%5]}</span></div><span class="font-semibold text-sm mt-3">${current(c.name)}</span></button>`).join("");el.querySelectorAll("button").forEach(b=>b.onclick=()=>{ $("#categoryFilter").value=b.dataset.cat; renderProducts()})}
function renderKits(){const el=$("#kitsGrid");el.innerHTML=state.kits.map(k=>`<div class="bg-white rounded-2xl shadow-sm hover:shadow-xl transition flex flex-col overflow-hidden"><div class="h-48 bg-surface-container relative overflow-hidden"><img src="${imgFor(k)}" class="w-full h-full object-cover" alt="${current(k.name)}"><div class="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent"></div><div class="absolute bottom-3 left-3 right-3 flex justify-between items-end"><span class="bg-white text-on-surface text-xs font-bold px-2 py-1 rounded">${current(k.badge)||"Destaque"}</span><span class="text-white font-bold">${money(k.price)}</span></div></div><div class="p-4 flex flex-col flex-1"><h3 class="text-xl font-semibold">${current(k.name)}</h3><p class="text-sm text-on-surface-variant mt-2 flex-1">${current(k.description)}</p><button data-kit="${k.id}" class="mt-4 w-full py-2.5 rounded-lg bg-surface-container-highest hover:bg-secondary hover:text-white font-semibold">Adicionar ao carrinho</button></div></div>`).join("");el.querySelectorAll("[data-kit]").forEach(b=>b.onclick=()=>{const k=state.kits.find(x=>x.id==b.dataset.kit);(k.product_ids||[]).forEach(id=>add(id));toast(current(k.name)+" adicionado")})}
function renderFilters(){const sel=$("#categoryFilter");sel.innerHTML=`<option value="">Todas as categorias</option>`+state.categories.map(c=>`<option value="${c.id}">${current(c.name)}</option>`).join("")}
function renderProducts(){let ps=[...state.products].filter(p=>p.active!==false);const q=$("#searchInput").value.toLowerCase();const cat=$("#categoryFilter").value;const sort=$("#sortFilter").value;if(q)ps=ps.filter(p=>(current(p.name)+" "+current(p.description)).toLowerCase().includes(q));if(cat)ps=ps.filter(p=>String(p.category_id)===String(cat));if(sort==="priceAsc")ps.sort((a,b)=>a.price-b.price);if(sort==="priceDesc")ps.sort((a,b)=>b.price-a.price);if(sort==="name")ps.sort((a,b)=>current(a.name).localeCompare(current(b.name)));const el=$("#productGrid");el.innerHTML=ps.map(p=>`<article class="bg-white rounded-2xl shadow-sm hover:shadow-xl transition overflow-hidden group"><div class="h-44 bg-surface-container relative"><img src="${imgFor(p)}" class="w-full h-full object-cover group-hover:scale-105 transition" alt="${current(p.name)}"><div class="absolute top-2 left-2 flex gap-1">${p.tag?`<span class="bg-secondary text-white text-[10px] font-bold px-2 py-1 rounded">${current(p.tag)}</span>`:""}${p.featured?`<span class="bg-primary text-white text-[10px] font-bold px-2 py-1 rounded">★</span>`:""}</div></div><div class="p-4"><h3 class="font-semibold">${current(p.name)}</h3><p class="text-xs text-on-surface-variant mt-1">${current(p.description)||""}</p><div class="flex items-end justify-between mt-4"><div><span class="text-xs text-on-surface-variant">${p.unit||""}</span><div class="text-lg font-bold text-primary">${money(p.price)}</div>${p.old_price?`<del class="text-xs text-outline">${money(p.old_price)}</del>`:""}</div><button data-add="${p.id}" class="w-10 h-10 rounded-full bg-secondary-container text-white flex items-center justify-center hover:bg-secondary"><span class="material-symbols-outlined">add_shopping_cart</span></button></div></div></article>`).join("")||`<div class="col-span-full text-center py-12 text-on-surface-variant">Nenhum produto encontrado.</div>`;el.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>add(b.dataset.add))}
function add(id){const p=state.products.find(x=>String(x.id)===String(id));if(!p)return;const row=state.cart.find(x=>String(x.id)===String(id));if(row)row.qty++;else state.cart.push({id:p.id,qty:1});saveCart();renderCart();toast(current(p.name)+" adicionado ao carrinho")}
function remove(id){state.cart=state.cart.filter(x=>String(x.id)!==String(id));saveCart();renderCart()}
function change(id,d){const x=state.cart.find(x=>String(x.id)===String(id));if(x){x.qty+=d;if(x.qty<=0)remove(id)}saveCart();renderCart()}
function saveCart(){localStorage.setItem("rf_cart",JSON.stringify(state.cart));$("#cartCount").textContent=state.cart.reduce((s,x)=>s+x.qty,0)}
function renderCart(){const el=$("#cartItems");let total=0;el.innerHTML=state.cart.map(x=>{const p=state.products.find(p=>String(p.id)===String(x.id));if(!p)return"";total+=p.price*x.qty;return`<div class="flex gap-3 border-b pb-3"><img src="${imgFor(p)}" class="w-16 h-16 rounded-lg object-cover"><div class="flex-1"><div class="font-semibold text-sm">${current(p.name)}</div><div class="text-primary font-bold text-sm">${money(p.price*x.qty)}</div><div class="flex items-center gap-2 mt-2"><button data-minus="${p.id}" class="w-7 h-7 rounded bg-surface-container">−</button><span>${x.qty}</span><button data-plus="${p.id}" class="w-7 h-7 rounded bg-surface-container">+</button><button data-remove="${p.id}" class="ml-auto text-error text-xs">Remover</button></div></div></div>`}).join("")||`<div class="text-center py-10 text-on-surface-variant">Carrinho vazio.</div>`;$("#cartTotal").textContent=money(total);el.querySelectorAll("[data-minus]").forEach(b=>b.onclick=()=>change(b.dataset.minus,-1));el.querySelectorAll("[data-plus]").forEach(b=>b.onclick=()=>change(b.dataset.plus,1));el.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>remove(b.dataset.remove));saveCart()}
function renderSteps(){const labels={pt:["Escolha","Monte o carrinho","Envie o pedido","Acompanhe"],en:["Choose","Build the cart","Send the order","Track it"],zh:["选择","加入购物车","发送订单","跟踪"],fr:["Choisissez","Composez le panier","Envoyez","Suivez"],chg:["Hlawula","Lunghisa cart","Rhumela oda","Landzelela"]}[state.lang];$("#steps").innerHTML=labels.map((x,i)=>`<div class="text-center p-5 bg-white/10 rounded-2xl"><div class="w-12 h-12 mx-auto rounded-full bg-secondary-container flex items-center justify-center text-white font-bold">${i+1}</div><h3 class="font-semibold mt-3">${x}</h3><p class="text-sm opacity-80 mt-1">${["Pesquise produtos e compare preços.","Ajuste quantidades e veja o total.","O pedido pode ser partilhado pelo WhatsApp.","A equipa confirma e actualiza o estado."][i]}</p></div>`).join("")}
function renderFaq(){const faq=[["Preciso criar uma conta?","Não para fazer o pedido. O cliente pode comprar sem registo."],["Quando o pedido fica confirmado?","Depois de a equipa verificar stock, zona de entrega e forma de pagamento."],["Posso alterar um pedido?","Sim, contacte o Rancho Flexível pelo WhatsApp o mais cedo possível."],["Como acompanho o pedido?","O administrador pode actualizar o estado do pedido."]];$("#faq").innerHTML=faq.map(x=>`<details class="bg-surface-container-low rounded-xl p-4"><summary class="font-semibold cursor-pointer">${x[0]}</summary><p class="text-sm text-on-surface-variant mt-2">${x[1]}</p></details>`).join("")}
function renderAll(){renderCategories();renderFilters();renderKits();renderProducts();renderCart();renderSteps();renderFaq();$("#year").textContent=new Date().getFullYear();if(state.settings.hero_image)$("#heroImage").src=state.settings.hero_image;if(state.settings.contact_email)$("#footerContact").innerHTML=`${state.settings.contact_email}<br>${state.settings.whatsapp||""}`}
$("#searchInput").oninput=renderProducts;$("#categoryFilter").onchange=renderProducts;$("#sortFilter").onchange=renderProducts;
$("#cartBtn").onclick=()=>$("#cartDrawer").classList.remove("hidden");$("#closeCart").onclick=()=>$("#cartDrawer").classList.add("hidden");$("#cartOverlay").onclick=()=>$("#cartDrawer").classList.add("hidden");
$("#checkoutBtn").onclick=()=>{if(!state.cart.length){toast("Adicione produtos primeiro.");return}location.href="checkout.html"};
$("#languageSelect").value=state.lang;$("#languageSelect").onchange=e=>{state.lang=e.target.value;localStorage.setItem("rf_lang",state.lang);renderAll();applyI18n()};
load();
