import { supabase } from './data.js';

const S={products:[],categories:[],combos:[],settings:{},cart:JSON.parse(localStorage.getItem('rf_cart')||'[]'),filter:'all',search:'',sort:'default'};
const $=s=>document.querySelector(s);
const txt=v=>typeof v==='string'?v:(v?.pt||v?.en||Object.values(v||{})[0]||'');
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=v=>`${Number(v||0).toLocaleString('pt-MZ',{minimumFractionDigits:2,maximumFractionDigits:2})} MZN`;
const img=p=>String(p?.image_url||p?.image||p?.photo_url||p?.imageUrl||'').trim();
const available=p=>p&&p.active!==false&&!(p.stock!==null&&p.stock!==undefined&&Number(p.stock)<=0);
const setting=(...keys)=>{for(const k of keys){let v=S.settings[k];if(v!==undefined&&v!==null&&String(v).trim()!=='')return v?.value??v}return ''};
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function toast(m){const e=$('#toast');if(!e)return;e.textContent=m;e.classList.remove('hidden');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.add('hidden'),1800)}
function count(){const n=S.cart.reduce((a,x)=>a+Number(x.qty||0),0);$('#cartCount')&&($('#cartCount').textContent=n);$('#rfStickyCount')&&($('#rfStickyCount').textContent=`${n} ${n===1?'produto selecionado':'produtos selecionados'}`)}
function save(){localStorage.setItem('rf_cart',JSON.stringify(S.cart));count();renderCart()}
function add(p){if(!available(p))return;const r=S.cart.find(x=>String(x.id)===String(p.id));r?r.qty++:S.cart.push({id:p.id,name:p.name,price:Number(p.price||0),old_price:Number(p.old_price||0),image_url:img(p),qty:1});save();toast(`${txt(p.name)} adicionado ao pedido.`)}
function catIcon(n){const x=norm(n);if(/latic|leite|dairy/.test(x))return'🥛';if(/fresc|frut|veget/.test(x))return'🥬';if(/carn|meat/.test(x))return'🥩';if(/bebid|drink|agua|sumo/.test(x))return'🧃';if(/limpez|clean/.test(x))return'🧹';if(/higien|hygiene/.test(x))return'🧼';if(/merce|grocery/.test(x))return'🛒';return'🛍️'}
function renderCategories(){const b=$('#categories');if(!b)return;const all=[{id:'all',name:'Todos'},...S.categories];b.innerHTML=all.map(c=>`<button type="button" data-cat="${esc(c.id)}" class="rf-cat shrink-0 bg-white border rounded-2xl px-4 py-3 text-center"><div class="text-2xl">${c.id==='all'?'🛒':catIcon(txt(c.name))}</div><div class="text-xs font-bold mt-1">${esc(txt(c.name))}</div></button>`).join('');b.querySelectorAll('[data-cat]').forEach(x=>x.onclick=()=>{S.filter=x.dataset.cat;$('#categoryFilter')&&($('#categoryFilter').value=S.filter);renderProducts()})}
function renderProducts(){const g=$('#productGrid');if(!g)return;let a=S.products.filter(p=>S.filter==='all'||String(p.category_id)===String(S.filter));if(S.search)a=a.filter(p=>norm(txt(p.name)+' '+txt(p.description)).includes(norm(S.search)));if(S.sort==='priceAsc')a.sort((x,y)=>x.price-y.price);if(S.sort==='priceDesc')a.sort((x,y)=>y.price-x.price);if(S.sort==='name')a.sort((x,y)=>txt(x.name).localeCompare(txt(y.name)));g.innerHTML=a.length?a.map(p=>{const ok=available(p),promo=Number(p.old_price)>Number(p.price),u=img(p);return `<article class="rf-card flex flex-col"><div class="rf-img">${u?`<img src="${esc(u)}" alt="${esc(txt(p.name))}" loading="lazy">`:'🛒'}</div><div class="p-4 flex flex-col flex-1"><div class="flex justify-between gap-2"><h3 class="font-bold text-sm">${esc(txt(p.name))}</h3>${promo?'<span class="rf-promo">PROMOÇÃO</span>':''}</div><p class="text-xs text-on-surface-variant mt-2">${esc(txt(p.description))}</p><div class="mt-auto pt-4">${promo?`<span class="text-xs line-through text-gray-400">${money(p.old_price)}</span>`:''}<strong class="block text-primary text-lg">${money(p.price)}</strong><button type="button" data-add="${esc(p.id)}" ${ok?'':'disabled'} class="w-full mt-3 py-2.5 rounded-xl font-bold ${ok?'bg-primary text-white':'rf-unavailable'}">${ok?'Adicionar':'Indisponível'}</button></div></div></article>`}).join(''):'<div class="col-span-full py-12 text-center">Nenhum produto encontrado.</div>';g.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const p=S.products.find(x=>String(x.id)===String(b.dataset.add));p&&add(p)})}
function renderCombos(){const g=$('#kitsGrid');if(!g)return;g.innerHTML=S.combos.length?S.combos.map(c=>{const ids=Array.isArray(c.product_ids)?c.product_ids:[],items=ids.map(id=>S.products.find(p=>String(p.id)===String(id))).filter(Boolean),u=img(c)||img(items[0]);return `<article class="rf-card flex flex-col"><div class="rf-img">${u?`<img src="${esc(u)}" alt="${esc(txt(c.name))}" loading="lazy">`:'🛒'}</div><div class="p-4 flex flex-col flex-1"><span class="text-xs text-secondary font-bold">Combo do Mês</span><h3 class="text-lg font-bold mt-1">${esc(txt(c.name))}</h3><p class="text-sm mt-2">${esc(txt(c.description))}</p><div class="mt-3 text-xs"><b>Este combo inclui:</b><ul class="mt-1">${items.map(p=>`<li>✓ ${esc(txt(p.name))}</li>`).join('')||'<li>Produtos do combo a definir.</li>'}</ul></div><div class="mt-auto pt-4 flex justify-between items-center"><b class="text-primary">${money(c.price)}</b><button type="button" data-combo="${esc(c.id)}" class="px-3 py-2 rounded-xl bg-secondary-container text-white font-bold">Adicionar</button></div></div></article>`}).join(''):'<div class="col-span-full text-center py-10">Nenhum combo disponível.</div>';g.querySelectorAll('[data-combo]').forEach(b=>b.onclick=()=>{const c=S.combos.find(x=>String(x.id)===String(b.dataset.combo));(c?.product_ids||[]).forEach(id=>{const p=S.products.find(x=>String(x.id)===String(id));p&&add(p)})})}
function totals(){let sub=0,save=0;for(const r of S.cart){const p=S.products.find(x=>String(x.id)===String(r.id)),q=Number(r.qty||0),price=Number(p?.price??r.price??0),old=Number(p?.old_price??r.old_price??0);sub+=price*q;save+=Math.max(0,old-price)*q}return{sub,save}}
function renderCart(){const b=$('#cartItems');if(!b)return;if(!S.cart.length){b.innerHTML='<div class="text-center py-12">O pedido está vazio.</div>';['cartSubtotal','cartSaving','cartTotal'].forEach(id=>{const e=$('#'+id);e&&(e.textContent='0 MZN')});return}b.innerHTML=S.cart.map((r,i)=>{const p=S.products.find(x=>String(x.id)===String(r.id)),u=img(p||r);return `<div class="flex gap-3 border rounded-xl p-3"><div class="w-16 h-16 bg-gray-100 rounded-lg overflow-hidden">${u?`<img src="${esc(u)}" class="w-full h-full object-cover">`:''}</div><div class="flex-1"><b class="text-sm">${esc(txt(p?.name||r.name))}</b><div class="text-primary font-bold">${money(p?.price??r.price)}</div><div class="flex gap-2 items-center mt-2"><button data-minus="${i}">−</button><span>${r.qty}</span><button data-plus="${i}">+</button><button data-remove="${i}" class="ml-auto text-red-600 text-xs">Remover</button></div></div></div>`}).join('');b.querySelectorAll('[data-minus]').forEach(x=>x.onclick=()=>{S.cart[+x.dataset.minus].qty--;if(S.cart[+x.dataset.minus].qty<=0)S.cart.splice(+x.dataset.minus,1);save()});b.querySelectorAll('[data-plus]').forEach(x=>x.onclick=()=>{S.cart[+x.dataset.plus].qty++;save()});b.querySelectorAll('[data-remove]').forEach(x=>x.onclick=()=>{S.cart.splice(+x.dataset.remove,1);save()});const t=totals();$('#cartSubtotal').textContent=money(t.sub);$('#cartSaving').textContent=money(t.save);$('#cartTotal').textContent=money(t.sub)}
function openCart(){renderCart();$('#cartDrawer')?.classList.remove('hidden');document.body.classList.add('overflow-hidden')}function closeCart(){$('#cartDrawer')?.classList.add('hidden');document.body.classList.remove('overflow-hidden')}
function renderCheckout(){const b=$('#checkoutSummary');if(!b)return;const t=totals();b.innerHTML=S.cart.map(r=>{const p=S.products.find(x=>String(x.id)===String(r.id));return `<div class="flex justify-between text-sm"><span>${esc(txt(p?.name||r.name))} × ${r.qty}</span><b>${money((p?.price??r.price)*r.qty)}</b></div>`}).join('')+`<hr><div class="flex justify-between"><span>Subtotal</span><b>${money(t.sub)}</b></div><div class="flex justify-between"><span>Poupança</span><b>${money(t.save)}</b></div><div class="flex justify-between"><span>Taxa de serviço</span><b>A definir</b></div><div class="flex justify-between text-lg font-bold"><span>Total</span><b>${money(t.sub)}</b></div>`}
function fees(n){const keys={Maputo Cidade:['delivery_maputo','maputo_delivery'],Zonas Circunvizinhas:['delivery_zonas','delivery_zonas_circunvizinhas'],Matola:['delivery_matola'],'Levantamento Gratis':['delivery_pickup','delivery_levantamento']};return Number(setting(...(keys[n]||[]))||({"Maputo Cidade":400,"Zonas Circunvizinhas":700,Matola:1000,"Levantamento Gratis":0}[n]||0))}
function openCheckout(){if(!S.cart.length){toast('Adicione produtos primeiro.');return}const d=$('#delivery');if(d)d.innerHTML='<option value="">Seleccione forma de entrega *</option>'+['Maputo Cidade','Zonas Circunvizinhas','Matola','Levantamento Gratis'].map(n=>`<option value="${esc(n)}">${esc(n)} — ${fees(n)?money(fees(n)):'Grátis'}</option>`).join('');renderCheckout();$('#checkoutModal')?.classList.remove('hidden')}
function finish(e){e?.preventDefault();const n=$('#customerName')?.value.trim(),p=$('#customerPhone')?.value.trim(),d=$('#delivery')?.value,pay=$('#payment')?.value,a=$('#address')?.value.trim(),s=document.querySelector('input[name="substitution"]:checked')?.value||'contact',o=$('#notes')?.value.trim();if(!n||!p||!d||!pay){toast('Preencha os campos obrigatórios.');return}const t=totals(),wa=setting('whatsapp_number','whatsapp','phone');if(!wa){toast('Número de WhatsApp não configurado.');return}const sub={contact:'Contactar antes',equivalent:'Sim, por produto equivalente',none:'Não substituir'}[s],lines=S.cart.map(r=>{const q=Number(r.qty||0),x=S.products.find(z=>String(z.id)===String(r.id));return `• ${txt(x?.name||r.name)} x${q} — ${money((x?.price??r.price)*q)}`}).join('\n');const msg=`*Novo pedido — Rancho Flexível*\n\n${lines}\n\n*Total:* ${money(t.sub)}\n*Entrega:* ${d}\n*Pagamento:* ${pay}\n*Substituições:* ${sub}\n*Cliente:* ${n}\n*Telefone:* ${p}\n*Endereço:* ${a||'Não informado'}\n*Observações:* ${o||'Nenhuma'}`;window.open(`https://wa.me/${String(wa).replace(/\D/g,'')}?text=${encodeURIComponent(msg)}`,'_blank')}
async function load(){try{const [p,c,k]=await Promise.all([supabase.from('products').select('*'),supabase.from('categories').select('*'),supabase.from('combos').select('*')]);S.products=p.data||[];S.categories=c.data||[];S.combos=k.data||[]}catch(e){console.error('public load',e)}try{const r=await supabase.from('site_settings').select('*');for(const x of r.data||[]){const key=x.key||x.name;if(key)S.settings[key]=x.value??x.content??x.text??x.data??''}}catch(e){console.error('settings load',e)}renderCategories();renderProducts();renderCombos();renderCart();count();$('#year')&&($('#year').textContent=new Date().getFullYear())}
function bind(){if(window.__rfV3Bound)return;window.__rfV3Bound=true;$('#cartBtn')?.addEventListener('click',openCart);$('#closeCart')?.addEventListener('click',closeCart);$('#cartOverlay')?.addEventListener('click',closeCart);$('#checkoutBtn')?.addEventListener('click',openCheckout);$('#closeCheckout')?.addEventListener('click',()=>$('#checkoutModal')?.classList.add('hidden'));$('#backCheckout')?.addEventListener('click',()=>$('#checkoutModal')?.classList.add('hidden'));$('#finishWhatsApp')?.addEventListener('click',finish);$('#checkoutForm')?.addEventListener('submit',finish);$('#searchInput')?.addEventListener('input',e=>{S.search=e.target.value;renderProducts()});$('#categoryFilter')?.addEventListener('change',e=>{S.filter=e.target.value;renderProducts()});$('#sortFilter')?.addEventListener('change',e=>{S.sort=e.target.value;renderProducts()});const st=document.createElement('div');st.id='rfSticky';st.innerHTML='<span id="rfStickyCount" class="font-extrabold text-primary">0 produtos selecionados</span><button type="button">🛒 Ver pedido</button>';document.body.appendChild(st);st.querySelector('button').onclick=openCart}
function style(){if($('#rf-v3-style'))return;const s=document.createElement('style');s.id='rf-v3-style';s.textContent='#rfSticky{position:fixed;left:50%;bottom:14px;transform:translateX(-50%);z-index:60;width:min(620px,calc(100% - 24px));display:flex;align-items:center;justify-content:space-between;gap:12px;background:#fff;border:1px solid #c1c9bf;border-radius:18px;padding:10px 12px 10px 16px;box-shadow:0 12px 35px rgba(0,0,0,.16)}#rfSticky button{border:0;background:#fd9d27;color:#fff;border-radius:12px;padding:10px 16px;font-weight:800;cursor:pointer}.rf-img{height:190px;background:#eef5f7;display:flex;align-items:center;justify-content:center;overflow:hidden}.rf-img img{width:100%;height:100%;object-fit:cover}.rf-card{background:#fff;border:1px solid #dbe3dd;border-radius:18px;overflow:hidden}.rf-promo{background:#e5482f;color:#fff;font-size:11px;font-weight:800;padding:4px 8px;border-radius:999px}.rf-unavailable{background:#e8ece9!important;color:#69726c!important;cursor:not-allowed!important}.rf-fullname{white-space:normal;overflow-wrap:anywhere}@media(max-width:640px){#rfSticky{bottom:8px}.rf-img{height:160px}}';document.head.appendChild(s)}
style();bind();load();