-- RANCHO FLEXÍVEL — SUPABASE SCHEMA
create extension if not exists pgcrypto;

create table if not exists profiles(
 id uuid primary key references auth.users(id) on delete cascade,
 email text,
 full_name text,
 role text not null default 'customer' check(role in ('admin','customer')),
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);

create table if not exists categories(
 id bigint generated by default as identity primary key,
 name jsonb not null,
 description jsonb default '{}'::jsonb,
 icon text,
 image_url text,
 active boolean not null default true,
 sort_order int not null default 0,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);

create table if not exists products(
 id text primary key,
 name jsonb not null,
 description jsonb default '{}'::jsonb,
 category_id bigint references categories(id) on delete set null,
 price numeric(12,2) not null default 0,
 old_price numeric(12,2),
 stock int not null default 0,
 sku text,
 unit text,
 tag jsonb default '{}'::jsonb,
 image_url text,
 active boolean not null default true,
 featured boolean not null default false,
 sort_order int not null default 0,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);

create table if not exists bundles(
 id text primary key,
 name jsonb not null,
 description jsonb default '{}'::jsonb,
 price numeric(12,2) not null default 0,
 product_ids jsonb not null default '[]'::jsonb,
 image_url text,
 badge jsonb default '{}'::jsonb,
 active boolean not null default true,
 sort_order int not null default 0,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);

create table if not exists customers(
 id uuid primary key default gen_random_uuid(),
 name text not null,
 phone text,
 email text,
 address text,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);

create table if not exists orders(
 id uuid primary key default gen_random_uuid(),
 order_number text unique not null,
 customer_id uuid references customers(id) on delete set null,
 customer_name text not null,
 customer_phone text,
 address text,
 delivery_zone text,
 delivery_fee numeric(12,2) default 0,
 total numeric(12,2) not null default 0,
 status text not null default 'new' check(status in ('new','confirmed','preparing','ready','delivered','cancelled')),
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);

create table if not exists order_items(
 id uuid primary key default gen_random_uuid(),
 order_id uuid not null references orders(id) on delete cascade,
 product_id text references products(id) on delete set null,
 product_name text,
 quantity int not null default 1,
 unit_price numeric(12,2) not null default 0,
 created_at timestamptz not null default now()
);

create table if not exists site_settings(
 key text primary key,
 value jsonb not null default '{}'::jsonb,
 updated_at timestamptz not null default now()
);

create table if not exists site_content(
 key text primary key,
 value jsonb not null default '{}'::jsonb,
 updated_at timestamptz not null default now()
);

create table if not exists banners(
 id bigint generated by default as identity primary key,
 title jsonb,
 subtitle jsonb,
 button_text jsonb,
 link text,
 image_url text,
 active boolean default true,
 sort_order int default 0,
 created_at timestamptz default now(),
 updated_at timestamptz default now()
);

create table if not exists delivery_zones(
 id bigint generated by default as identity primary key,
 name jsonb not null,
 fee numeric(12,2) not null default 0,
 active boolean default true,
 sort_order int default 0,
 created_at timestamptz default now(),
 updated_at timestamptz default now()
);

create table if not exists media(
 id uuid primary key default gen_random_uuid(),
 bucket text not null,
 path text not null,
 url text not null,
 alt jsonb default '{}'::jsonb,
 created_at timestamptz default now()
);

alter table profiles enable row level security;
alter table categories enable row level security;
alter table products enable row level security;
alter table bundles enable row level security;
alter table customers enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;
alter table site_settings enable row level security;
alter table site_content enable row level security;
alter table banners enable row level security;
alter table delivery_zones enable row level security;
alter table media enable row level security;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from profiles where id=auth.uid() and role='admin'); $$;

drop policy if exists "public read categories" on categories;
create policy "public read categories" on categories for select using(active=true);
drop policy if exists "admin manage categories" on categories;
create policy "admin manage categories" on categories for all using(public.is_admin()) with check(public.is_admin());

drop policy if exists "public read products" on products;
create policy "public read products" on products for select using(active=true);
drop policy if exists "admin manage products" on products;
create policy "admin manage products" on products for all using(public.is_admin()) with check(public.is_admin());

drop policy if exists "public read bundles" on bundles;
create policy "public read bundles" on bundles for select using(active=true);
drop policy if exists "admin manage bundles" on bundles;
create policy "admin manage bundles" on bundles for all using(public.is_admin()) with check(public.is_admin());

drop policy if exists "admin profiles" on profiles;
create policy "admin profiles" on profiles for select using(auth.uid()=id or public.is_admin());
drop policy if exists "admin update profile" on profiles;
create policy "admin update profile" on profiles for update using(auth.uid()=id or public.is_admin());

drop policy if exists "public settings" on site_settings;
create policy "public settings" on site_settings for select using(true);
drop policy if exists "admin settings" on site_settings;
create policy "admin settings" on site_settings for all using(public.is_admin()) with check(public.is_admin());

drop policy if exists "public content" on site_content;
create policy "public content" on site_content for select using(true);
drop policy if exists "admin content" on site_content;
create policy "admin content" on site_content for all using(public.is_admin()) with check(public.is_admin());

drop policy if exists "public banners" on banners;
create policy "public banners" on banners for select using(active=true);
drop policy if exists "admin banners" on banners;
create policy "admin banners" on banners for all using(public.is_admin()) with check(public.is_admin());

drop policy if exists "public delivery" on delivery_zones;
create policy "public delivery" on delivery_zones for select using(active=true);
drop policy if exists "admin delivery" on delivery_zones;
create policy "admin delivery" on delivery_zones for all using(public.is_admin()) with check(public.is_admin());

drop policy if exists "admin customers" on customers;
create policy "admin customers" on customers for all using(public.is_admin()) with check(public.is_admin());

drop policy if exists "create orders public" on orders;
create policy "create orders public" on orders for insert with check(true);
drop policy if exists "admin orders" on orders;
create policy "admin orders" on orders for select using(public.is_admin());
create policy "admin update orders" on orders for update using(public.is_admin()) with check(public.is_admin());

drop policy if exists "create order items public" on order_items;
create policy "create order items public" on order_items for insert with check(true);
drop policy if exists "admin order items" on order_items;
create policy "admin order items" on order_items for select using(public.is_admin());

drop policy if exists "public media" on media;
create policy "public media" on media for select using(true);
drop policy if exists "admin media" on media;
create policy "admin media" on media for all using(public.is_admin()) with check(public.is_admin());

-- Storage: execute in Supabase SQL editor after creating the bucket 'site-images'.
-- Recommended bucket visibility: public for product/banner image URLs.
-- Storage policies should restrict INSERT/UPDATE/DELETE to authenticated admins.
